name: application
description: project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_sliders: ^19.3.45
  flutter_localizations:
      sdk: flutter
  animated_splash_screen:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.0.0
  firebase_auth: ^1.0.1
  google_fonts: any
  audioplayers:
  provider: ^5.0.0
  http: ^0.13.0
  shared_preferences: ^2.0.4
  flutter_html: ^2.0.0-nullsafety.0
  file_picker: ^3.0.0
  path_provider: ^2.0.1
  camera: ^0.8.0

  device_apps:
  android_intent:
  url_launcher:
  # save_in_gallery: ^0.1.3
  image: ^3.0.8
  flutter_svg: ^0.22.0
  images_picker: ^1.0.0
  connectivity: ^3.0.2
  location: ^4.1.1
  google_maps_flutter: ^2.0.1
  tuple: 2.0.0
  permission_handler: ^6.1.0
# Provides server & web apps with the ability to load, manipulate and save images with various image file formats PNG, JPEG, GIF, BMP, WebP, TIFF, TGA, PSD, PVR, and OpenEXR.

# Allows painting & displaying Scalable Vector Graphics 1.1 files
  package_info: ^2.0.0

  flutter_launcher_icons: ^0.9.0
  page_view_indicators: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_native_splash: ^1.2.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  assets:
    - images/strings.png
    - images/platform.png
    - images/handsclosed.png
    - images/handsbaloon.png
    - images/handsdown.png
    - images/handsopen.png
    - images/legs.png
    - images/expo/baloon.png
    - images/expo/brain.png
    - images/expo/smile.png
    - images/expo/meditate.png
    - images/poo.png
    - images/glasses1.png
    - images/glasses2.png
    - images/glasses3.png
    - images/glasses4.png
    - images/glasses5.png
    - images/World_1.jpg
    - images/logo.png
    - images/face.png
    - images/color.png
    - images/hands1.png
    - images/color(ff6f6ca7).png
    - images/color(ffa6d6c3).png
    - images/color(ffdabfa0).png
    - images/color(ffefb3e2).png
    - images/body.png
    - images/brows.png
    - images/mouth.png
    - images/eyes.png
    - images/right_arrow.png
    - images/left_arrow.png
    - images/sheba.png
    - images/shibi_pages/1.png
    - images/shibi_pages/2.png
    - images/shibi_pages/3.png
    - images/shibi_pages/angel.png
    - images/shibi_pages/clean.png
    - images/shibi_pages/dirty.png
    - images/shibi_pages/green.png
    - images/shibi_pages/lose.png
    - images/shibi_pages/win.png
    - images/shibi_pages/gangster.png
    - images/shibi_pages/money.png
    - images/World_1.jpg
    - images/expo/brain.jpg
    - images/expo/smile.jpg
    - images/expo/meditate.jpg
    - images/expo/baloon.jpg
    - images/meditate1.png
    - images/ColorSlider.png
    - images/spotify.png
    - images/apple-music.png
    - images/youtube.png
    - images/skater2.png
    - images/skater.png
    - images/talk.png
    - images/cloud1.png
    - images/cloud2.png
    - images/needle.png
    - images/boom1.png
    - images/boom2.png
    - images/Soldier1.png
    - images/Soldier2.png
    - images/Soldier3.png
    - images/Soldier4.png
    - images/Yellow_Star.png
    - images/Blue_Star.png
    - images/Green_Star.png
    - images/Pink_Star.png
    - images/thumbsup.png
    - images/smiley.png
    - images/human.png
    - images/cloud.png
    - images/talky.png
    - images/coin.png
    - images/staron.png
    - images/staroff.png
    - images/expo/ppl.png
    - images/Shoola.png
    - images/meditate9.png

    - music/meditation.mp3
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages